method: grid

metric:
  name: val_discounted_mean_rmse_h100_g0.99
  goal: minimize

command:
  - ${env}
  - python
  - -m
  - scripts.train_sweep
  - --epochs
  - 50
  - --eval_every
  - 1
  - --num_workers
  - 0
  - ${args}

parameters:
  model:
    values:
      - ml_dmd
      - ml_linear_dynamics

  data_path:
    values: [data/trajectories/nonlinear/pendulum/long]

  lr:
    values: [1e-5, 1e-4, 1e-3]

  weight_decay:
    values: [0.0, 1e-6]

  batch_size:
    values: [2048]

  expansion_degree:
    values: [3, 5, 7, 10]

  expansion_type:
    values: ["specific"]

  sine_cosine_expansion:
    values: ["true"]

  trajectory_length:
    values: ["long"]

  bias:
    values: ["true"]