method: grid

metric:
  name: score
  goal: minimize

command:
  - ${env}
  - python
  - -m
  - scripts.train_and_eval
  - --model
  - <MODEL_NAME>
  - --data_path
  - <DATA_PATH>
  - --epochs
  - 50
  - ${args}

parameters:
  lr:
    values: [1e-4, 5e-4, 1e-3]

  weight_decay:
    values: [0.0, 1e-8, 1e-6]

  batch_size:
    values: [32, 64]