method: grid

metric:
  name: score
  goal: minimize

command:
  - ${env}
  - C:\Users\danie\OneDrive - Danmarks Tekniske Universitet\Dokumenter\10. semester\MSc Thesis\Cerebellum-DL-Models\.env\Scripts\python.exe
  - -m
  - scripts.train_and_eval
  - --model
  - manual_expansion_ml_dmd
  - --data_path
  - data/trajectories/nonlinear/vanderpol_trajectory.npz
  - --epochs
  - 3
  - ${args}

parameters:
  lr:
    values: [1e-4, 5e-4]