project: koopman-operator-learning
entity: DeepLearningP4Destruction
method: grid

metric:
  name: val_rollout_rmse_h20
  goal: minimize

command:
  - ${env}
  - python
  - -m
  - scripts.train_sweep
  - --eval_horizon_divisor
  - 5
  - --num_workers
  - 4
  - ${args}

parameters:
  model:
    values:
      - regression_dmd

  data_path:
    values:
      - data/trajectories/linear/inward_spiral/dt_0.05
      - data/trajectories/linear/harmonic_oscillator/dt_0.05
      - data/trajectories/linear/saddle_point/dt_0.05
      - data/trajectories/linear/degenerate_node/dt_0.05
      - data/trajectories/nonlinear/closed_small/dt_0.05
      - data/trajectories/nonlinear/closed_large/dt_0.05
      - data/trajectories/nonlinear/closed_trig_small/dt_0.05
      - data/trajectories/nonlinear/closed_trig_medium/dt_0.05
      - data/trajectories/nonlinear/closed_trig_large/dt_0.05
      - data/trajectories/nonlinear/vanderpol/dt_0.05
      - data/trajectories/nonlinear/duffing/dt_0.05
      - data/trajectories/nonlinear/lotka_volterra/dt_0.05
      - data/trajectories/nonlinear/pendulum/dt_0.05
      - data/trajectories/nonlinear/lorenz/dt_0.05

  expansion_degree:
    values: [3, 5, 7]

  regression_rollout_mode:
    values: ["DMD"]

  expansion_type:
    values: ["general"]

  sine_cosine_expansion:
    values: ["false", "true"]

  bias:
    values: ["true"]

  normalize_state:
    values: ["true"]